### ISSUE TITLE
First of type

### ISSUE THREAD

**Issue by tomhodgins** [xem/miniMinifier#14]
```css
p:nth-of-type(1) {
  color: blue;
}
```

## correct minification

```css
p:first-of-type{color:blue}
```

- `:first-of-type` is shorter than `:nth-of-type(1)`

## CSSnano output

```css
p:nth-of-type(1){color:blue}
```

- left `:nth-of-type(1)`

I wonder what other `:nth-of-type`-like things can be optimized for size!
