### ISSUE TITLE
nested @media query

### ISSUE THREAD

**Issue by tomhodgins** [xem/miniMinifier#16]
```css
@media (min-width: 500px) {
  @media (min-height: 500px) {
    :root {
      background: lime;
    }
  }
}
```

## correct minification

```css
@media(min-width:500px)and(min-height:500px){:root{background:lime}}
```

- combine both media queries with `and`
- remove space after `@media`

## CSSnano output

```css
@media (min-width:500px){@media (min-height:500px){:root{background:lime}}}
```

- leaves both `@media` queries intact
- leaves space after `@media` before brackets
