### ISSUE TITLE
remove zero units

### ISSUE THREAD

**Issue by tomhodgins** [xem/miniMinifier#18]
```css
.remove-zero-unit {
  max-height: 0%;
  height: 0%;
  font-size: calc(0%);
  transform: rotateZ(0deg);
}
```

## correct minification

```css
.remove-zero-unit{max-height:0;height:0;font-size:0;transform:rotate(0)}
```

- removes `%` and `deg` units where they can be safely eliminated

## CSSnano output

```css
.remove-zero-unit{max-height:0%;height:0%;font-size:0%;transform:rotate(0deg)}
```

- can remove unit from % on `height` and `max-height` properties
- can remove `deg` from `0deg`
- can remove `%` if final simplification from calc is `0%`
