### ISSUE TITLE
CSS replace hex with color name if it's shorter

### ISSUE THREAD

**Issue by xem** [xem/miniMinifier#5]
ex #c0c0c0 => silver

**Comment by tomhodgins** [comment]
```css
.beige {
  color: #f5f5bc;
}
```

you can replace `#f5f5bc` with `beige`
