### ISSUE TITLE
Reduce Aspect Ratio Fraction

### ISSUE THREAD

**Issue by tomhodgins** [xem/miniMinifier#9]
```css
@media (min-aspect-ratio: 160000000000/90000000000) {
  :root {
    background: lime;
  }
}
```

## correct minification

```css
@media (min-aspect-ratio:16/9){:root{background:lime}}
```

- ratio value can be reduced

## CSSnano output

```css
@media (min-aspect-ratio:160000000000/90000000000){:root{background:lime}}
```

- ratio numbers keep unneeded `0000000000`
